### ISSUE TITLE
Object Storage API

### ISSUE THREAD

**Issue by JeanCollas** [ovh/csharp-ovh#14]
I have just developed a .Net (Net Standard 2.0) lib to play with the OVH Object Storage services.
This might be useful for some people reaching this repository:
https://github.com/JeanCollas/OpenStack.NetSwiftClient

**Comment by LukeMarlin** [comment]
Hi,

Thank you for bringing your project to our attention.
I've let the Object Storage team know that this SDK exists, so if we get any inquiries we might consider redirecting users to this one instead of the official python SDK if it does not meet customer's requirement.
