### ISSUE TITLE
Github documentation is obsolete.

### ISSUE THREAD

**Issue by laloutre87** [ovh/csharp-ovh#19]
Right from the start , the documentation says : 

    CredentialRequest requestPayload = new CredentialRequest(
        new List<AccessRight>(){
            new AccessRight("GET", "/me"),
        }
    );

This method takes 2 parameters.

**Comment by LukeMarlin** [comment]
Thank you for bringing that to my attention.
I'll be looking into this as soon as possible! (most probably tomorrow maximum)

**Comment by LukeMarlin** [comment]
Fixed with #20 and #21 for now.
When I'm done with #13 I'll update the nuget package and do a full check of documentation.

In the meantime I'll leave this issue opened as there might well be more obsolete stuff :)

**Comment by philippeVerney** [comment]
This same code snippet also misses "using Ovh.Api.Models;"
By doing a copy paste of the code snippet, the compiler could not find "CredentialRequest" class without this "using".

**Comment by LukeMarlin** [comment]
I'll check this before the week end, thanks for the report

**Comment by philippeVerney** [comment]
I think you also miss a code line to make the same code snippet working : "client.ConsumerKey = credentialRequestResult.ConsumerKey;"
Here is a proposed change. Sorry, I am too lazy to make a fork and a PR.

.. code:: csharp

    using Ovh.Api;
    using Ovh.Api.Models; // TO BE ADDED!!!!!!
    using System;
    using System.Collections.Generic;

    namespace api_tester
    {
        class Program
        {
            static void Main(string[] args)
            {
                Client client = new Client();
                CredentialRequest requestPayload = new CredentialRequest(
                    new List<AccessRight>(){
                        new AccessRight("GET", "/me")
                    },
                    "https://redirect.url" // CHANGE THIS URL IF YOU DON'T WANT TO SEE AN UNREACHING WEBPAGE AFTER YOU LOGGED IN
                );

                CredentialRequestResult credentialRequestResult =
                    client.RequestConsumerKey(requestPayload);
                Console.Write(
                    String.Format("Please visit {0} to authenticate ",
                        credentialRequestResult.ValidationUrl));
                Console.WriteLine("and press enter to continue");
                Console.ReadLine();

                client.ConsumerKey = credentialRequestResult.ConsumerKey; // TO BE ADDED!!!!!!
                PartialMe me = client.Get<PartialMe>("/me");

                Console.WriteLine(
                    String.Format("Welcome, {0}", me.firstname));
                Console.WriteLine(
                    String.Format("Btw, your 'consumerKey' is {0}",
                        credentialRequestResult.ConsumerKey));
                Console.ReadLine();
            }
        }

        class PartialMe
        {
            public string firstname { get; set; }
            public string name { get; set; }
        }
    }

**Comment by philippeVerney** [comment]
Actually, I made the PR.

**Comment by LukeMarlin** [comment]
Thank you very much!
I guess that I skipped that missing line because I had a key registered in my env, so it worked for me anyway :)

I'll check and merge is as soon as possible!

**Comment by philippeVerney** [comment]
Hi Luke,

In documentation paragraph "Install a new mail redirection", this code line does not compile : client.Post(String.Format("/email/domain/{0}/redirection", domain), payload);

Indeed, payload is a dictionary but the post method requires a simple string as a second parameter, not a dictionary.
Could you correct this please?

**Comment by LukeMarlin** [comment]
@philippeVerney Fixed with #27.

Made me wonder why I dropped the simple API of `Call<T>([...], object data)` and forced users to specify a `Y` for the input data type. The only thing that is done is serialization by Json.Net.

If we still had the old way, that example would still be working. I might remove these `<T,Y>` versions and use `object` instead of `Y` soon as I see no benefits to using them.

If you can confirm it's alright, I'll merge the PR and close that issue.
