### ISSUE TITLE
No responses to any api calls

### ISSUE THREAD

**Issue by andrew5834** [ovh/csharp-ovh#41]
Hello,

I've created a script token and using it to authenticate my app (eu ovh).
But I'm not getting any response from the api to any request I send.
For example, I'm doing PartialMe me = await client.GetAsync<PartialMe>("/me"); and my app freezes because there is no response. Same for any other endpoint.
Is there a way to get any help with this?

It would be great to have a basic example app (full solution) that I could use to try and pinpoint the issue.

Thank you
Andrew

**Comment by LukeMarlin** [comment]
What if you wait for an extended period of time, do you get a timeout?
Can you contact `api.ovh.com` properly from where you run the script, in another way (curl, browser)?

**Comment by andrew5834** [comment]
No, I don't seem to get any timeout. The app will remain frozen for several minutes.
I can open api.ovh.com just fine in my browser.

**Comment by LukeMarlin** [comment]
Would you be able to try out the branch 4.0.0?
Also, can you provide your complete test code so we can be sure it's directly linked to the lib?

**Comment by andrew5834** [comment]
[Moderdomain - Copy.zip](https://github.com/ovh/csharp-ovh/files/4035538/Moderdomain.-.Copy.zip)
This is my source code.
I'll try the 4.0.0 and let you know. Thanks

**Comment by andrew5834** [comment]
Just tried it with 4.0.0. - the same behavior, the app freezes

**Comment by LukeMarlin** [comment]
Thank you, we'll look into it!

**Comment by LukeMarlin** [comment]
This is now fixed in 4.0.3. Be aware that this build introduces some breaking changes though.
Can you try with it?

**Comment by andrew5834** [comment]
I'm on 5d049450d40fc05f156725ada4728e1c712e80fb and I see no problems so far.

**Comment by LukeMarlin** [comment]
Nice to hear.
I'll close the issue for now then. Feel free to reopen it if needed!
