### ISSUE TITLE
Dot Net Core 3.1, Can not find Ovh namespace.

### ISSUE THREAD

**Issue by hieu-n** [ovh/csharp-ovh#47]
I'm using Dot Net Core 3.1. I installed `csharp-ovh` by using the following command:

`dotnet add package csharp-ovh`

Then I tried `using Ovh.Api`.  `Ovh` can not be found/resolved.

**Comment by LukeMarlin** [comment]
Indeed, you are right, it seems we built the package incorrectly.
Fixing in progress.

**Comment by Namaneo** [comment]
We just fixed the incorrect NuGet package build. Version 4.0.4 of the library correctly contains the binaries now. Can you try it and tell us if it's OK on your side?

**Comment by hieu-n** [comment]
Thank you very much. The problem is fixed.
