### ISSUE TITLE
No definition for "RequestConsumerKey"

### ISSUE THREAD

**Issue by Snakzi** [ovh/csharp-ovh#50]
`CredentialRequestResult credentialRequestResult =
                client.RequestConsumerKey(requestPayload);
`

seems to be obsolete? I'm trying to get the consumer key but "RequestConsumerKey" seems like it does not exist.

**Comment by Snakzi** [comment]
`await client.RequestConsumerKeyAsync(requestPayload);`

does work though. So maybe just edit the readme file :)

**Comment by Namaneo** [comment]
Indeed, `README` file is wrong, we dropped all synchronized implementations of the library when we bumped the version to 4.0: `RequestConsumerKeyAsync` is now the only way to go. Thanks for pointing this out, will fix it!

**Comment by LukeMarlin** [comment]
Thank you @Snakzi for spotting and reporting this, and thanks to @Namaneo for quickly fixing this!
