### ISSUE TITLE
An exception occured while trying to issue the HTTP call ??

### ISSUE THREAD

**Issue by ruicaramalho** [ovh/csharp-ovh#58]
Even with the simple example (bellow) I alway receive the error `An exception occured while trying to issue the HTTP call`
How can I debug this issue?

~~~~csharp
        public static async Task<string> MyInfo()
        {
            try
            {
                Log.Info($"Connecting to OVH...");
                Client client = new Client();
                Log.Info($"Connected");
                PartialMe me = await client.GetAsync<PartialMe>("/me");
                Log.Info($"Hello {me.firstname}!");
                return me.firstname;
            }
            catch (Exception ex)
            {
                Log.Warn(ex.Message);
                return null;
            }
        }
~~~~

I have a `.ovh.conf` file

**Comment by ruicaramalho** [comment]
The problem was TLS.  by default Visual Studio is not using TLS12 as the first option.

Please change the constructor in `Client.cs` to:

~~~~csharp
        public Client(string endpoint = null, string applicationKey = null,
            string applicationSecret = null, string consumerKey = null,
            TimeSpan? defaultTimeout = null, char parameterSeparator = ',',
            HttpClient httpClient = null, string confFileName = ".ovh.conf") : this()
        {
            LoadConfiguration(endpoint, applicationKey, applicationSecret, consumerKey, parameterSeparator, confFileName);
            _defaultTimeout = defaultTimeout ?? _defaultTimeout;

            //specify to use TLS 1.2 as default connection
            ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12 | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls;

            _httpClient = httpClient ?? _httpClient ?? new HttpClient(handler);
        }
~~~~

**Comment by ruicaramalho** [comment]
Quick fix solution for the current version

Necessary references:
~~~~csharp
using System;
using Ovh.Api;
using System.Threading.Tasks;
using System.Net;
using System.Net.Http;
~~~~


~~~~csharp
        /// <summary>
        /// Customise our client.
        /// </summary>
        /// <returns></returns>
        internal static Client NoProxyClient()
        {
            //specify to use TLS 1.2 as default connection, otherwise it will not work...
            ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12 | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls;

            //Remove Proxy, In my case we have a proxy in the LAN
            HttpClientHandler handler = new HttpClientHandler
            {
                UseProxy = false
            };

            var httpClient = new HttpClient(handler);
            return new Client(null,null,null,null,null,',',httpClient);
        }

        public static async Task<string> MyInfo()
        {

            Client client = NoProxyClient();

            string me = await client.GetAsync("/me");
            return me;

        }
~~~~

**Comment by Namaneo** [comment]
Hello,

Thanks for opening an issue, and for your investigation!

I could not reproduce on my side, using a .NET Core 3.1 console application running on Windows 10 20H2. Looking at [the documentation](https://docs.microsoft.com/en-us/dotnet/api/system.net.servicepointmanager.securityprotocol?view=netstandard-2.0), starting with .NET Framework 4.7, it seems this configuration depends on the system: 
* Are you using an older framework?
* Are you using a Windows version that don't have it enabled?

In any case, `ServicePointManager.SecurityProtocol` alters the whole process, therefore we should not manipulate it from inside the library as per [Microsoft recommendations](https://docs.microsoft.com/en-us/dotnet/framework/network-programming/tls). However, you can apply that change in your own code if this is an acceptable solution for you.

**Comment by ruicaramalho** [comment]
I had the problem while debuging using Visual Studio  2017 in a windows 10 on a WebProject with for NetFramework 4.6.2.   
The fault is probably because of the IIS Express used by VS in debug.

Just want to add that the code is clean and well comented, well done.

**Comment by ruicaramalho** [comment]
The problem is VS in debug mode using the IIS Express.
