### ISSUE TITLE
Support for .NET Standard

### ISSUE THREAD

**Issue by Jotune** [ovh/csharp-ovh#8]
The project should be available in .NET Standard 2.0 more than in .NET Core 2.0.
.NET Standard 2.0 support .NET Core 2.0, .NET Framework 4.6.1+, Mono, Xamarin and UWP - [ref](https://docs.microsoft.com/fr-fr/dotnet/standard/net-standard)

Should I go for it ?

EDIT: It seems that ini-parser 2.5.2 does not support .NET Core nor .NET Standard (Warning NU1701). The ini-parser team planned support for version 3.

**Comment by LukeMarlin** [comment]
Indeed, nice catch.

And sure, go for it!
